### ISSUE TITLE
Doesn't seem to update after creating a new item

### ISSUE THREAD

**Issue by parkr** [jspahrsummers/GroceryList#17]
This is _such_ a cool project. Just what I've always wanted for dealing with my lists.

For some reason, my Simulator isn't updating the main listing when I add a new item to the list. This is what I saw after I created the item "Wheat Bread":

![screen shot 2014-02-08 at 9 34 15 pm](https://f.cloud.github.com/assets/237985/2118972/4b3a792a-9133-11e3-8bd9-8a29ee44cb32.png)

Pulling to update didn't help. Is this lag on GitHub's side?

**Comment by jspahrsummers** [comment]
Weird. I think there may be some caching-related issues in the code, but I haven't tracked them down completely yet.

Thanks for the bug reports!
