### ISSUE TITLE
Question – Regarding using subscribe:nil

### ISSUE THREAD

**Issue by bobspryn** [jspahrsummers/GroceryList#20]
In `GCYGroceryListViewModel.m` you have this code:

``` Objective-C
[[[[self.didBecomeActiveSignal
    flattenMap:^(GCYGroceryListViewModel *viewModel) {
        return [[[[viewModel.signInAction
            signalWithValue:nil]
            ignoreValues]
            concat:[RACSignal return:viewModel]]
            catchTo:[RACSignal empty]];
    }]
    flattenMap:^(GCYGroceryListViewModel *viewModel) {
        return [[[viewModel.loadItemsAction
            signalWithValue:nil]
            concat:[RACSignal return:RACUnit.defaultUnit]]
            catchTo:[RACSignal empty]];
    }]
    take:1]
    subscribe:nil];
```

I'm curious in particular about the `subscribe:nil`. I wondered how you handled this type of need to execute some actions/signals without really needing to subscribe to their values.  I was doing the same thing with `subscribe:nil` but felt a little dirty about it. Anything wrong with this practice?

**Comment by jspahrsummers** [comment]
Yes, it's a terrible idea. It'd probably be better to use `-[RACAction execute:]`.
