### ISSUE TITLE
Can't build with a fresh clone

### ISSUE THREAD

**Issue by jem-computer** [jspahrsummers/GroceryList#21]
Hey Justin - great app, learnt tons of RAC tricks by reading the source, but I just tried to get it running on my Mac and can't get it to compile :) / :(

I've:
- cloned
- created a new, non-empty repo & a new GitHub app
- filled in the UserSettings.xcconfig file
- ./script/bootstrap'd
- Build

The error I get is in `GroceryList-Prefix.pch` - `'UIKit/UIKit.h' file not found`. If I comment out that line I get the same error when it gets to `MobileCoreServices.h`.

I'm still new to iOS development so not sure if the error is a project config error or something on my end - any ideas?

I see that the frameworks are being included in the project settings; not sure what to do next.
![grocerylist xcodeproj 2014-03-09 12-44-29 2014-03-09 12-44-39](https://f.cloud.github.com/assets/591643/2367931/958f41ca-a788-11e3-95a0-fc90423ec5eb.png)

Thanks!

**Comment by jem-computer** [comment]
Update: restarted Xcode, that has gone away now but now it's not reading my UserSettings.xcconfig file - getting `GCY_CLIENT_ID and GCY_CLIENT_SECRET must be defined to connect to GitHub.` & `Define GCY_LIST_REPOSITORY to the owner/name of the repository to store the grocery list within.` even though they are defined. Hmm.

**Comment by jspahrsummers** [comment]
@jongd Would you mind uploading your project somewhere, so I can download it and see what's wrong?

**Comment by jem-computer** [comment]
Sure - http://c.jon.gd/1I3Z2y1g2J1S - (I removed the cloned dependencies to save space) - it's literally exactly the same as it was when I cloned it, just added the configuration file which doesn't seem to be being picked up.

**Comment by jspahrsummers** [comment]
@jongd Those definitions need to be _part of_ `GCC_PREPROCESSOR_DEFINITIONS`. They're deliberately on the same line in the README, so your case would look something like:

```
GCC_PREPROCESSOR_DEFINITIONS=$(inherited) GCY_LIST_REPOSITORY=jongd/gcy-lists GCY_CLIENT_ID=XXXX GCY_CLIENT_SECRET=XXXXXXX
```

**Comment by jem-computer** [comment]
oh wow, I'm sure I tried that - works fine now though. _shrug_ - sorry for the n00b issue and thanks for introducing me to preprocessor definitions :)

**Comment by jspahrsummers** [comment]
No problem, great to hear that it's working now!
