### ISSUE TITLE
Build errors in Xcode 5.1

### ISSUE THREAD

**Issue by Soryu** [jspahrsummers/GroceryList#22]
Xcode 5.1 (5B130a)

```
$ clang --version
Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix
```
## Deprecated compiler flags in .xcconfigs

```
clang: error: argument '-fcatch-undefined-behavior' is deprecated, use '-fsanitize=undefined-trap -fsanitize-undefined-trap-on-error' instead
```

In these files:
- ./External/ReactiveCocoaLayout/External/Archimedes/Configuration/Base/Configurations/Debug.xcconfig
- ./External/OctoKit/External/ReactiveCocoa/external/xcconfigs/Base/Configurations/Debug.xcconfig
- ./External/OctoKit/External/Mantle/Configuration/Base/Configurations/Debug.xcconfig
- ./External/ReactiveCocoaLayout/External/ReactiveCocoa/external/xcconfigs/Base/Configurations/Debug.xcconfig
- ./External/ReactiveViewModel/External/ReactiveCocoa/external/xcconfigs/Base/Configurations/Debug.xcconfig
## Unused consts in Mantle when compiling with `DEBUG`

```
./External/OctoKit/External/Mantle/Mantle/MTLManagedObjectAdapter.m:39:24: error: unused variable 'MTLManagedObjectAdapterErrorExceptionThrown' [-Werror,-Wunused-const-variable]`
./External/OctoKit/External/Mantle/Mantle/MTLJSONAdapter.m:19:24: error: unused variable 'MTLJSONAdapterErrorExceptionThrown' [-Werror,-Wunused-const-variable]`
```

I added `#ifdef DEBUG` to work around it quick’n’dirty
## Floating point conversion error
- `./GroceryList/GCYViewController.m:55:64: error: implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Werror,-Wconversion]`
## Configuration file not being found

The README says to put the file in the Configuration directory of the project, but the `./Configuration/GroceryList.xcconfig` includes it differently. Should be

```
#include "Configuration/UserSettings.xcconfig"
```

**Comment by kostiakoval** [comment]
I have the same issue.  I've tried to fix some of them but it seam like there are a lot of broken warnings in other submodules.
