### ISSUE TITLE
List doesn't refresh

### ISSUE THREAD

**Issue by kastiglione** [jspahrsummers/GroceryList#23]
This [change](https://github.com/jspahrsummers/GroceryList/commit/d696bffcae06496097b9f123d596023943a5ab25#diff-d390e56878983eb4bed5611204c03594R74) would appear to be the culprit. The `list` is loaded only once, when the `repository` is assigned to initially.

**Comment by jspahrsummers** [comment]
Does pull-to-refresh still work?

**Comment by kastiglione** [comment]
No. Nor does it refresh following the done shopping action.

**Comment by jspahrsummers** [comment]
Ah, quite right.
