### ISSUE TITLE
where is the definition of rcl_presentViewController: animated: ?

### ISSUE THREAD

**Issue by Tiger6688** [jspahrsummers/GroceryList#27]
where is the definition of rcl_presentViewController: animated:? not found in your project and reactiveCocoalayout

**Comment by kastiglione** [comment]
It's in the `rac-3.0` branch of ReactiveCocoaLayout. [Link](https://github.com/ReactiveCocoa/ReactiveCocoaLayout/blob/8e62ebedfa9ddaf1b78e77d7a4967b7397388de5/ReactiveCocoaLayout/UIViewController%2BRCLPresentationAdditions.h#L15-19).

**Comment by Tiger6688** [comment]
@kastiglione Thanks !
